<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BattlelogNotifier\NotifierOptions' => __DIR__ . '/src/BattlelogNotifier/NotifierOptions.php',
    'BattlelogNotifier\Notifier'        => __DIR__ . '/src/BattlelogNotifier/Notifier.php',
);