<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BattlelogNotifier\HttpClient'              => __DIR__ . '/src/BattlelogNotifier/HttpClient.php',
    'BattlelogNotifier\HttpClientOptions'       => __DIR__ . '/src/BattlelogNotifier/HttpClientOptions.php',
    'BattlelogNotifier\NotifierOptions'         => __DIR__ . '/src/BattlelogNotifier/NotifierOptions.php',
    'BattlelogNotifier\Notifier'                => __DIR__ . '/src/BattlelogNotifier/Notifier.php',
    'BattlelogNotifier\Stdlib\OptionsContainer' => __DIR__ . '/src/BattlelogNotifier/Stdlib/OptionContainer.php',
);